version: "3.7"

services:
  db:
    image: arangodb:latest
    environment:
      ARANGO_ROOT_PASSWORD: rootpassword
    ports:
      - 8529:8529
    volumes:
      - arangodb_data_container:/var/lib/arangodb3
      - arangodb_apps_data_container:/var/lib/arangodb3-apps
    command: "--query.memory-limit 50000 --query.max-runtime 30"
    # command: "--query.memory-limit 50000 --query.max-runtime 30 --database.auto-upgrade true"
volumes:
  arangodb_data_container:
  arangodb_apps_data_container:
